<?php 
return [
'name' => 'GMRE - Producciones', 
'website' => 'https://gmre.com.py', 
'phone' => '0981574711', 
'email_from' => 'admin@gmre.com.py', 
'maintenance_mode' => '0', 
'currency' => 'Gs', 
'purchase_min_amount' => '100', 
'shipping_default_value' => '11', 
'shipping_amount_min' => '1000', 
'shipping_method' => '2', 
'to_go' => '1', 
'social_facebook' => '#', 
'social_instagram' => '#', 
'social_twitter' => '#', 
'social_youtube' => '#', 
'social_whatsapp' => '#', 
'payment_method_cash' => '1', 
'payment_method_transfer' => '1', 
'payment_method_paypal' => '1', 
'payment_method_credit_card' => '1', 
'product_per_page' => '2', 
'product_per_page_random' => '3', 
'upload_server_path' => '/Users/juliofranco/Desktop/Programacion/gmreproducciones/public/uploads/', 
'upload_server_user_path' => '/Users/juliofranco/Desktop/Programacion/gmreproducciones/public/uploads_users/', 
'server_webapp_path' => '/Users/juliofranco/Desktop/Programacion/gmreproducciones/', 
] 
?>
